db.restaurants.find();
db.restaurants.find({},{ restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });
db.restaurants.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });
db.restaurants.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, "address.zipcode": 1 });
db.restaurants.find({ borough: "Bronx" });
db.restaurants.find({ borough: "Bronx" }).limit(5);
db.restaurants.find({ borough: "Bronx" }).skip(5).limit(5);
db.restaurants.find({ "grades.score": { $gt: 90 } });
db.restaurants.find({ grades: { $elemMatch: { score: { $gt: 80, $lt: 100 } } } });
db.restaurants.find({ "address.coord.0": { $lt: -95.754168 } });
db.restaurants.find({ cuisine: { $ne: "American " }, "grades.score": { $gt: 70 }, "address.coord.0": { $lt: -65.754168 }});
db.restaurants.find({ $expr: { $not: { $or: [ { $eq: ["$cuisine", "American "] }, { $lte: [{ $max: "$grades.score" }, 70] }, { $gte: [{ $arrayElemAt: ["$address.coord", 0] }, -65.754168] } ]}}});
db.restaurants.find({ cuisine: { $ne: "American "}, "grades.grade" : "A", borough: { $ne: "Brooklyn" }}).sort({ cuisine: -1});
db.restaurants.find({ name: /^Wil/ },{ _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });
db.restaurants.find({ name: /ces$/ },{ _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });
db.restaurants.find({ name: /Reg/ },{ _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });
db.restaurants.find({ borough: "Bronx", cuisine: { $in: ["American ", "Chinese"] }});
db.restaurants.find({ borough: { $in: ["Staten Island", "Queens", "Bronx", "Brooklyn"] }}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });
db.restaurants.find({ borough: { $nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"] }}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 });
